name: HTML CD

on:
  push:
    branches:
      - main

jobs:
  deliver:

    runs-on: ubuntu-latest

    steps:
      - name: Check repositorio
        uses: actions/checkout@v4

      - name: Delivery
        uses: actions/upload-artifact@v4
        with:
          name: atvsom1.zip
          path: |
            src/index.html
            src/style.css
            src/validarlogin.js
            test/validarLogin.test.js

  docker:
    needs: deliver
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build image
        run: docker build -t meu-site .

      - name: Test container
        run: |
          docker run -d -p 8080:80 --name teste meu-site
          sleep 5
          curl http://localhost:8080

      - name: Stop container
        run: docker stop teste
